# set up the default terminal
#ENV["TERM"]="linux"

Vagrant.configure("2") do |config|
  
  # set the image for the vagrant box
  config.vm.box = "generic/alpine312"
  ## Set the image version
  # config.vm.box_version = "15.2.31.212"

  # st the static IP for the vagrant box
  config.vm.network "private_network", ip: "192.168.50.4"
  
  # consifure the parameters for VirtualBox provider
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    #vb.cpus = 2
    #vb.customize ["modifyvm", :id, "--ioapic", "on"]
    #vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
    #vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
    #vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
  end
end
